version: '3.8'

services:
  qitops:
    build: .
    image: qitops-agent:latest
    container_name: qitops-agent
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://ollama:11434}
      - QITOPS_DEFAULT_LLM_PROVIDER=${QITOPS_DEFAULT_LLM_PROVIDER:-ollama}
      - QITOPS_DEFAULT_LLM_MODEL=${QITOPS_DEFAULT_LLM_MODEL:-mistral}
    volumes:
      - ./config:/root/.config/qitops
      - ./output:/app/output
    networks:
      - qitops-network
    command: ["run", "pr-analyze", "--pr", "${PR_NUMBER:-1}"]
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - qitops-network
    restart: unless-stopped

networks:
  qitops-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local
